---
- name: "停止集群的所有服务"
  systemd:
    name: "{{ item }}"
    state: stopped
    daemon_reload: yes
  with_items:
    - "keepalived"
    - "haproxy"
    - "etcd"
    - "kube-apiserver"
    - "kube-controller-manager"
    - "kube-scheduler"
    - "{% if container_runtime == 'containerd' %}containerd{% else %}docker{% endif %}"
    - "kubelet"
    - "kube-proxy"
  tags: purge

- name: "删除keepalived+haproxy"
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - "keepalived"
    - "haproxy"
    - "{% if container_runtime == 'containerd' %}containerd.io{% else %}docker-ce{% endif %}"
    - "chrony"
  tags: purge

- name: "删除节点二进制文件"
  file:
    path: "/usr/bin/{{ item }}"
    state: absent
  with_items:
    - "kube-apiserver"
    - "kube-controller-manager"
    - "kube-scheduler"
    - "crictl"
    - "kubelet"
    - "kube-proxy"
    - "helm"
    - "calicoctl"
  tags: purge

- name: "删除集群目录及文件"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/etcd"
    - "{{ cert.dir }}"
    - "{{ etcd.data_dir }}"
    - "{{ kubernetes.kubelet_dir }}"
    - "{{ docker.root }}"
    - "{{ docker.confdir }}"
    - "{{ containerd.root }}"
    - "/etc/containerd"
    - "/etc/kubernetes"
    - "/var/log/kubernetes"
    - "/var/log/calico"
    - "/opt/cni/bin"
    - "/root/.kube"
    - "/etc/cni/net.d"
    - "/var/log/chrony"
    - "/etc/crictl.yaml"
    - "/etc/bash_completion.d/crictl"
    - "/etc/keepalived"
    - "/etc/haproxy"
    - "/usr/lib/systemd/system/kube-apiserver.service"
    - "/usr/lib/systemd/system/kube-controller-manager.service"
    - "/usr/lib/systemd/system/kube-scheduler.service"
    - "/usr/lib/systemd/system/kubelet.service"
    - "/usr/lib/systemd/system/kube-proxy.service"
  tags: purge
