---
- name: "Generate calico yaml"
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items:
    - {src: "calico-etcd.yaml.j2", dest: "/tmp/calico-etcd.yaml"}
  tags: calico

- name: "Deploy calico"
  shell: "kubectl apply -f /tmp/calico-etcd.yaml"
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  tags: calico

- name: "检查calicoctl是否存在"
  shell: ls /usr/bin/calicoctl
  ignore_errors: true
  register: calicoctl_ready

- name: "复制calicoctl至/usr/bin"
  get_url:
    url: "https://github.com/projectcalico/calicoctl/releases/download/{{ calico.version }}/calicoctl-linux-amd64"
    owner: root
    group: root
    mode: 0750
    dest: /usr/bin/calicoctl
  when: calicoctl_ready.rc != 0
  tags: calico
