---
- name: restart_docker
  systemd:
    name: docker
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: restart_containerd
  systemd:
    name: containerd
    state: restarted
    enabled: yes
    daemon_reload: yes
