---
- name: "Create cni-plugins directory"
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items:
    - "/opt/cni/bin/"
    - "/etc/cni/net.d/"
  tags: dir

- name: "判断cni-plugins是否已经存在"
  shell: ls /tmp/cni-plugins-linux-amd64-{{kubernetes.cni_plugins_version}}.tgz
  ignore_errors: true
  register: cni_plugins_exist_ready

- name: Get cni-plugins
  when: cni_plugins_exist_ready.rc != 0
  get_url:
    url: "https://github.91chifun.workers.dev/https://github.com//containernetworking/plugins/releases/download/{{kubernetes.cni_plugins_version}}/cni-plugins-linux-amd64-{{kubernetes.cni_plugins_version}}.tgz"
    dest: /tmp/

- name: Install cni-plugins
  unarchive:
    src: "/tmp/cni-plugins-linux-amd64-{{kubernetes.cni_plugins_version}}.tgz"
    dest: /opt/cni/bin/
    remote_src: yes

- name: "拷贝cni-plugins 配置文件到/etc/cni/net.d"
  template:
    src: "cni-default.conf.j2"
    dest: "/etc/cni/net.d/cni-default.conf"
    owner: root
    group: root
    mode: 0644
